# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio          = [ 1, 3, 3]
sort_by        = "mtime"
sort_sensitive = false
sort_reverse   = true
sort_dir_first = false
sort_translit  = false
linemode       = "size"
show_hidden    = true
show_symlink   = true
scrolloff      = 5
mouse_events   = [ "click", "scroll" ]
title_format   = "Yazi: {cwd}"

[preview]
wrap            = "yes"
tab_size        = 2


[opener]
edit = [
    { run = "zed %s",           desc = "zed",  for = "unix", orphan = true },
	{ run = "bat --pager='less -R' --style=header,grid %s",
	                            desc = "bat",  for = "unix", block = true },
	{ run = "nvim %s",          desc = "nvim", for = "unix", block = true },
	{ run = "hx %s",            desc = "hx",   for = "unix", block = true },
	{ run = "code %s",          desc = "code", for = "unix", orphan = true },
	{ run = "code %s",          desc = "code",           for = "windows", orphan = true },
	{ run = "code -w %s",       desc = "code (block)",   for = "windows", block = true },
]
# reveal = [
# 	{ run = "xdg-open %d1",         desc = "Reveal", for = "linux" },
# 	{ run = "open -R %s1",          desc = "Reveal", for = "macos" },
# 	{ run = "explorer /select,%s1", desc = "Reveal", for = "windows", orphan = true },
# 	{ run = "termux-open %d1",      desc = "Reveal", for = "android" },
# 	{ run = "clear; exiftool %s1; echo 'Press enter to exit'; read _", desc = "Show EXIF", for = "unix", block = true },
# ]

[pick]
open_title  = "Open with Editor:"
open_origin = "hovered"
open_offset = [ 5, 2, 30, 17 ]
