theme = "catppuccin_mocha"

[editor]
line-number = "relative"
# mouse = true
# cursorline = true
# auto-save = true
# color-modes = true
#
# [editor.cursor-shape]
# insert = "bar"
# normal = "block"
# select = "underline"
#
# [editor.file-picker]
# hidden = false
#
# [editor.statusline]
# left = ["mode", "spinner"]
# center = ["file-name"]
# right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
# separator = "│"
#
# [editor.lsp]
# display-messages = true
# display-inlay-hints = true
#
# [keys.normal]
# # Your custom keybindings hereheme = "catppuccin_mocha"
#
# [editor]
# line-number = "relative"
# mouse = true
# cursorline = true
# auto-save = true
# color-modes = true
#
# [editor.cursor-shape]
# insert = "bar"
# normal = "block"
# select = "underline"
#
# [editor.file-picker]
# hidden = false
#
# [editor.statusline]
# left = ["mode", "spinner"]
# center = ["file-name"]
# right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
# separator = "│"
#
# [editor.lsp]
# display-messages = true
# display-inlay-hints = true
#
# [keys.normal]
# # Your custom keybindings here
